services:
  reviewbot:
    build: .
    container_name: reviewbot
    restart: always
    ports:
      - "5000:8000"
    environment:
      - FLASK_SECRET=CHANGE_ME_TO_RANDOM_STRING
      - DATABASE_PATH=/app/data/database.db
      - SEPAY_API_KEY=RPCNXBH0ND3SW6EVAR8CPXTIWKQ4GOGYH1VY9SSCWBJI2ZQRJUX35SFJ4YUN9DYL
      - SEPAY_API_SECRET=
      - SEPAY_ACCOUNT_ID=220208888888
      - SEPAY_BANK_CODE=STB
      - SEPAY_BANK_NAME=Sacombank
    volumes:
      - ./data:/app/data

networks:
  default:
    name: reviewbot-net
